---
name: Test
on: [workflow_call] # yamllint disable-line rule:truthy

jobs:
  bats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run bats tests
        run: |
          bash ./test/install_bats.bash
          ./test/lib/bats-core/bin/bats ./test
        shell: bash
